# Generated by Django 5.0.1 on 2024-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_options_product_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="elaboration",
            field=models.CharField(
                choices=[("Kitchen", "Kitchen"), ("Bar", "Bar"), ("Waiter", "Waiter")],
                default="Kitchen",
                max_length=13,
                verbose_name="Order paid",
            ),
        ),
    ]
