# Generated by Django 5.0.1 on 2024-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_date_order_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cash",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.CharField(
                choices=[("Transfer", "Transfer"), ("Cash", "Cash"), ("Both", "Both")],
                default="Cash",
                max_length=13,
                verbose_name="Order paid",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transfer",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Transfer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=13,
                verbose_name="Order state",
            ),
        ),
    ]
