# Generated by Django 5.0.1 on 2024-01-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_cash_order_paid_order_transfer_and_more"),
        ("products", "0002_alter_product_options_product_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agregate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregateitemAgregate",
                        to="products.aggregate",
                        verbose_name="Aggregate",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregateitemItems",
                        to="orders.items",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aggregate Item",
                "verbose_name_plural": "Aggregates Items",
            },
        ),
    ]
