# Generated by Django 5.0.1 on 2024-01-26 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_aggregateitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aggregateitems",
            old_name="agregate",
            new_name="aggregate",
        ),
    ]
