# Generated by Django 5.0.1 on 2024-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_rename_agregate_aggregateitems_aggregate"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="state",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Elaborating", "Elaborating"),
                    ("Finished", "Finished"),
                ],
                default="Delivered",
                max_length=13,
                verbose_name="Item state",
            ),
        ),
    ]
