# Generated by Django 5.0.1 on 2024-01-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lounge",
            name="lounge_name",
            field=models.CharField(max_length=255, verbose_name="Lounge name"),
        ),
    ]
