# Generated by Django 5.0.1 on 2024-01-25 08:02

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser('mangel', 'mangel@gmail.com', 'admin')

class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_alter_lounge_local_alter_table_lounge"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
