# Generated by Django 5.0.1 on 2024-01-25 11:00

from django.db import migrations
from django.contrib.auth import get_user_model

def create_user(apps,schema_editor):
    User = get_user_model()
    User.objects.create_superuser('mangel','mangelryujin@gmail.com','admin')
    

class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
