# Generated by Django 5.0.1 on 2024-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20240125_0600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("chef", "chef"),
                    ("waiter", "waiter"),
                    ("barman", "barman"),
                    ("economic", "economic"),
                    ("administrador", "administrador"),
                ],
                default="waiter",
                max_length=13,
            ),
        ),
    ]
